import * as dotenv from "dotenv";
import path from "node:path";
import { fileURLToPath } from "node:url";
import fs from "node:fs";
import crypto from "node:crypto";

// Load .env from repo root regardless of cwd (npm run dev -w apps/gateway sets cwd to apps/gateway)
let loadedEnvPath: string | null = null;
try {
  const __filename = fileURLToPath(import.meta.url);
  const __dirname = path.dirname(__filename);
  const candidates = [
    path.resolve(".env"),
    path.resolve(path.join(process.cwd(), ".env")),
    path.resolve(path.join(__dirname, "../../../.env")),
    path.resolve(path.join(__dirname, "../../.env")),
    path.resolve("/app/.env"),
  ];
  for (const p of candidates) {
    if (fs.existsSync(p)) {
      dotenv.config({ path: p });
      loadedEnvPath = p;
      break;
    }
  }
  // Fallback to default dotenv (cwd)
  if (!process.env.MASTER_KEY) dotenv.config();
} catch {
  /* ignore: dotenv fallback */
  dotenv.config();
}

function isPlaceholderMaster(v: string | undefined): boolean {
  if (!v) return true;
  return v.includes("change-me") || v === "fgk-master-dev-key" || v.trim().length < 16;
}
function isPlaceholderEncryption(v: string | undefined): boolean {
  if (!v) return true;
  const hex = v.replace(/[^0-9a-f]/gi, "");
  return hex.length < 64 || v.includes("0123456789abcdef0123456789abcdef");
}
function tryLoadPersistedFallback(): void {
  // If .env missing (Docker without env_file), reuse keys from data/.gateway-keys.json
  if (!isPlaceholderMaster(process.env.MASTER_KEY) && !isPlaceholderEncryption(process.env.ENCRYPTION_KEY)) return;
  const candidates = [
    path.resolve("data/.gateway-keys.json"),
    path.resolve(path.join(process.cwd(), "data/.gateway-keys.json")),
    path.resolve("/app/data/.gateway-keys.json"),
  ];
  try {
    const __filename = fileURLToPath(import.meta.url);
    const __dirname = path.dirname(__filename);
    candidates.unshift(path.resolve(path.join(__dirname, "../../../data/.gateway-keys.json")));
    candidates.unshift(path.resolve(path.join(__dirname, "../../data/.gateway-keys.json")));
  } catch { /* ignore: __dirname unavailable */ }
  for (const p of candidates) {
    try {
      if (fs.existsSync(p)) {
        const j = JSON.parse(fs.readFileSync(p, "utf-8"));
        if (isPlaceholderMaster(process.env.MASTER_KEY) && j.MASTER_KEY) process.env.MASTER_KEY = j.MASTER_KEY;
        if (isPlaceholderEncryption(process.env.ENCRYPTION_KEY) && j.ENCRYPTION_KEY) process.env.ENCRYPTION_KEY = j.ENCRYPTION_KEY;
        if (!isPlaceholderMaster(process.env.MASTER_KEY) || !isPlaceholderEncryption(process.env.ENCRYPTION_KEY)) {
          console.warn(`[config] Restored keys from ${p}`);
          break;
        }
      }
    } catch { /* ignore: key file unreadable */ }
  }
}
function ensureKeysAutoGenerated() {
  let changed = false;
  if (isPlaceholderMaster(process.env.MASTER_KEY)) {
    const gen = `fgk-master-${crypto.randomBytes(16).toString("hex")}`;
    process.env.MASTER_KEY = gen;
    changed = true;
    // Never log full key — even dev logs can leak via Docker/CI. Show prefix only.
    // Full value is persisted to .env / data/.gateway-keys.json for the operator.
    console.warn(`[config] Auto-generated MASTER_KEY=${gen.slice(0, 14)}... (redacted, see .env or data/.gateway-keys.json)`);
  }
  if (isPlaceholderEncryption(process.env.ENCRYPTION_KEY)) {
    const gen = crypto.randomBytes(32).toString("hex");
    process.env.ENCRYPTION_KEY = gen;
    changed = true;
    console.warn(`[config] Auto-generated ENCRYPTION_KEY=${gen.slice(0, 8)}... (no valid .env value found)`);
  }
  if (changed && loadedEnvPath) {
    try {
      let content = fs.readFileSync(loadedEnvPath, "utf-8");
      if (process.env.MASTER_KEY) {
        if (content.includes("MASTER_KEY=")) content = content.replace(/^MASTER_KEY=.*$/m, `MASTER_KEY=${process.env.MASTER_KEY}`);
        else content += `\nMASTER_KEY=${process.env.MASTER_KEY}\n`;
      }
      if (process.env.ENCRYPTION_KEY) {
        if (content.includes("ENCRYPTION_KEY=")) content = content.replace(/^ENCRYPTION_KEY=.*$/m, `ENCRYPTION_KEY=${process.env.ENCRYPTION_KEY}`);
        else content += `\nENCRYPTION_KEY=${process.env.ENCRYPTION_KEY}\n`;
      }
      fs.writeFileSync(loadedEnvPath, content);
      console.warn(`[config] Persisted auto-generated keys to ${loadedEnvPath}`);
    } catch (e) {
      console.warn(`[config] Could not persist auto-generated keys to ${loadedEnvPath}:`, (e as Error).message);
    }
  } else if (changed) {
    // No .env file found (e.g. Docker without env_file) — persist to data dir for next restart
    try {
      const dataDir = loadedEnvPath ? path.dirname(loadedEnvPath) : path.resolve("data");
      const persistPath = path.join(dataDir, ".gateway-keys.json");
      // also try /app/data
      const candidates = [persistPath, "/app/data/.gateway-keys.json", path.resolve(process.cwd(), "data/.gateway-keys.json")];
      const target = candidates[0];
      fs.mkdirSync(path.dirname(target), { recursive: true });
      fs.writeFileSync(target, JSON.stringify({ MASTER_KEY: process.env.MASTER_KEY, ENCRYPTION_KEY: process.env.ENCRYPTION_KEY }, null, 2));
      console.warn(`[config] Persisted auto-generated keys to ${target} (fallback, no .env found)`);
    } catch { /* ignore: fallback persist failed */ }
  }
}
tryLoadPersistedFallback();
ensureKeysAutoGenerated();

/** Default fallback order (single tier). Single source — parseTiers() reuses it. */
export const DEFAULT_FALLBACK_TIER: readonly string[] = [
  "kiraai",
  "pollinations",
  "llm7-io",
  "kilo-code",
  "agnes-ai",
  "ollama-cloud",
  "nvidia-nim",
  "orcarouter",
  "openrouter",
  "unorouter",
  "claude-code",
  "codex",
  "groq",
  "cerebras",
  "google-gemini",
  "github-models",
  "modelscope",
  "chutes-ai",
  "sambanova",
  "siliconflow",
  "cohere",
  "mistral-ai",
  "cloudflare-workers-ai",
  "ovhcloud-ai-endpoints",
  "aion-labs",
  "z-ai-zhipu-ai",
  "experientiallabs",
  "opencode",
  "freeai",
  "cline",
  "b-ai",
  "tokenharbor",
  "together",
  "fireworks",
  "novita",
  "deepseek",
  "grok-xai",
  "alibaba-cloud-model-studio",
  "nscale",
  "nebius",
  "ai21-labs",
  "anthropic",
];

function parseTiers(): string[][] {
  try {
    const raw = process.env.FALLBACK_TIERS;
    if (!raw) return [[...DEFAULT_FALLBACK_TIER]];
    const parsed = JSON.parse(raw) as unknown;
    if (!Array.isArray(parsed) || parsed.length === 0) return [[...DEFAULT_FALLBACK_TIER]];
    // Validate: array of arrays of non-empty strings, cap size to prevent DoS
    const tiers: string[][] = [];
    for (const tier of parsed) {
      if (!Array.isArray(tier)) return [[...DEFAULT_FALLBACK_TIER]];
      const clean = tier.filter((p): p is string => typeof p === "string" && p.trim().length > 0).slice(0, 60);
      if (clean.length === 0) return [[...DEFAULT_FALLBACK_TIER]];
      tiers.push(clean);
      if (tiers.length >= 8) break;
    }
    return tiers;
  } catch {
    return [[...DEFAULT_FALLBACK_TIER]];
  }
}

function parseKeys(env: string | undefined): string[] {
  if (!env) return [];
  return env.split(",").map((s) => s.trim()).filter(Boolean);
}

function parseBoolEnv(v: string | undefined): boolean {
  if (!v) return false;
  const s = v.trim().toLowerCase();
  return s === "1" || s === "true" || s === "yes" || s === "on";
}

export const config = {
  port: parseInt(process.env.PORT || "7373", 10),
  nodeEnv: process.env.NODE_ENV || "development",
  logLevel: process.env.LOG_LEVEL || "info",
  corsOrigin: process.env.CORS_ORIGIN || "*",
  databaseUrl: process.env.DATABASE_URL || "file:./data.db",
  redisUrl: process.env.REDIS_URL || "",
  masterKey: process.env.MASTER_KEY || "fgk-master-dev-key",
  encryptionKey: process.env.ENCRYPTION_KEY || "0123456789abcdef0123456789abcdef0123456789abcdef0123456789abcdef",
  defaultModel: process.env.DEFAULT_MODEL || "auto",
  fallbackTiers: parseTiers(),
  circuitBreakerThreshold: parseInt(process.env.CIRCUIT_BREAKER_THRESHOLD || "5", 10),
  circuitBreakerCooldownMs: parseInt(process.env.CIRCUIT_BREAKER_COOLDOWN_MS || "30000", 10),
  // Experiential Labs OpenAI-compatible base (used in registry)
  experientialApiBase: process.env.EXPERIENTIAL_API_BASE || "https://api.experientiallabs.ai/v1",
  // Vector 2 flags - validated with safe defaults
  semanticCacheEnabled: parseBoolEnv(process.env.SEMANTIC_CACHE_ENABLED),
  semanticCacheThreshold: (() => {
    const v = parseFloat(process.env.SEMANTIC_THRESHOLD || "0.92");
    if (isNaN(v) || v < 0 || v > 1) {
      console.warn(`[config] Invalid SEMANTIC_THRESHOLD=${process.env.SEMANTIC_THRESHOLD}, fallback to 0.92 (must be 0..1)`);
      return 0.92;
    }
    return v;
  })(),
  semanticCacheTtlSec: (() => {
    const v = parseInt(process.env.CACHE_TTL_S || "3600", 10);
    if (isNaN(v) || v <= 0) {
      console.warn(`[config] Invalid CACHE_TTL_S=${process.env.CACHE_TTL_S}, fallback to 3600`);
      return 3600;
    }
    return Math.min(v, 86400 * 7); // cap 7 days
  })(),
  embeddingModel: (process.env.EMBEDDING_MODEL || "cohere/embed-english-v3.0").split(",")[0].trim(),
  embeddingModels: (process.env.EMBEDDING_MODEL || "cohere/embed-english-v3.0").split(",").map((s) => s.trim()).filter(Boolean),
  embeddingFallbacks: (process.env.EMBEDDING_FALLBACKS || "nvidia-nim/nvidia/nv-embed-v1,cloudflare-workers-ai/@cf/baai/bge-large-en-v1.5").split(",").map((s) => s.trim()).filter(Boolean),
  compressionEnabled: parseBoolEnv(process.env.COMPRESSION_ENABLED),
  // token budget for compression pipeline (harness 02 Build Context) - default 80% of context
  compressionMaxTokens: (() => {
    const v = parseInt(process.env.COMPRESSION_MAX_TOKENS || "4096", 10);
    if (isNaN(v) || v <= 0) return 4096;
    return Math.min(v, 32000);
  })(),
  costRoutingEnabled: parseBoolEnv(process.env.COST_ROUTING_ENABLED),
  // configurable weights for cost-router (harness 06 Decide Tools) - env overrides fix doc/code drift
  costWeight: (() => {
    const v = parseFloat(process.env.COST_WEIGHT || "5");
    return isNaN(v) || v < 0 ? 5 : v;
  })(),
  latencyWeight: (() => {
    const v = parseFloat(process.env.LATENCY_WEIGHT || "0.0005");
    return isNaN(v) || v < 0 ? 0.0005 : v;
  })(),
  headroomWeight: (() => {
    const v = parseFloat(process.env.HEADROOM_WEIGHT || "0.3");
    return isNaN(v) || v < 0 ? 0.3 : v;
  })(),
  // success-rate weight: demote providers failing often even before breaker opens
  successWeight: (() => {
    const v = parseFloat(process.env.SUCCESS_WEIGHT || "2");
    return isNaN(v) || v < 0 ? 2 : v;
  })(),
  // semantic cache advanced flags (harness 01 Retrieve)
  semanticCacheMaxMemEntries: (() => {
    const v = parseInt(process.env.SEMANTIC_CACHE_MAX_MEM || "1000", 10);
    return isNaN(v) || v <= 0 ? 1000 : Math.min(v, 10000);
  })(),
  semanticCacheScanCap: (() => {
    const v = parseInt(process.env.SEMANTIC_CACHE_SCAN_CAP || "200", 10);
    return isNaN(v) || v <= 0 ? 200 : Math.min(v, 1000);
  })(),
  analyticsRetentionDays: (() => {
    const v = parseInt(process.env.ANALYTICS_RETENTION_DAYS || "30", 10);
    if (isNaN(v) || v <= 0) return 30;
    return Math.min(v, 365);
  })(),
  providerTimeoutMs: (() => {
    const v = parseInt(process.env.PROVIDER_TIMEOUT_MS || "25000", 10);
    return isNaN(v) || v <= 0 ? 25000 : Math.min(v, 120000);
  })(),
  providerTimeoutAutoMs: (() => {
    const v = parseInt(process.env.PROVIDER_TIMEOUT_AUTO_MS || "8000", 10);
    return isNaN(v) || v <= 0 ? 8000 : Math.min(v, 30000);
  })(),
  providerParallelAuto: (() => {
    const v = parseInt(process.env.PROVIDER_PARALLEL_AUTO || "3", 10);
    return isNaN(v) || v <= 0 ? 3 : Math.min(v, 5);
  })(),
  // ---- Web tools (gateway-hosted web_search + web_fetch) ----
  webToolsEnabled: parseBoolEnv(process.env.WEB_TOOLS_ENABLED),
  webSearchProvider: (process.env.WEB_SEARCH_PROVIDER || "tavily").trim().toLowerCase(),
  tavilyApiKey: (process.env.TAVILY_API_KEY || "").trim(),
  braveApiKey: (process.env.BRAVE_API_KEY || "").trim(),
  serperApiKey: (process.env.SERPER_API_KEY || "").trim(),
  jinaApiKey: (process.env.JINA_API_KEY || "").trim(),
  webFetchTimeoutMs: (() => {
    const v = parseInt(process.env.WEB_FETCH_TIMEOUT_MS || "8000", 10);
    return isNaN(v) || v <= 0 ? 8000 : Math.min(v, 30000);
  })(),
  webFetchMaxBytes: (() => {
    const v = parseInt(process.env.WEB_FETCH_MAX_BYTES || "500000", 10);
    return isNaN(v) || v <= 0 ? 500000 : Math.min(v, 2_000_000);
  })(),
  webSearchMaxResults: (() => {
    const v = parseInt(process.env.WEB_SEARCH_MAX_RESULTS || "5", 10);
    return isNaN(v) || v <= 0 ? 5 : Math.min(v, 10);
  })(),
  webToolsMaxIterations: (() => {
    const v = parseInt(process.env.WEB_TOOLS_MAX_ITERATIONS || "3", 10);
    return isNaN(v) || v <= 0 ? 3 : Math.min(v, 5);
  })(),
  webCacheTtlSec: (() => {
    const v = parseInt(process.env.WEB_CACHE_TTL_S || "3600", 10);
    return isNaN(v) || v <= 0 ? 3600 : Math.min(v, 86400);
  })(),
  // ---- P8 Adaptive Routing ----
  adaptiveRoutingEnabled: parseBoolEnv(process.env.ADAPTIVE_ROUTING_ENABLED),
  adaptiveEmaAlpha: (() => {
    const v = parseFloat(process.env.ADAPTIVE_EMA_ALPHA || "0.3");
    if (isNaN(v) || v <= 0 || v > 1) return 0.3;
    return v;
  })(),
  // ---- P8 Per-model quota ----
  perModelQuotaEnabled: parseBoolEnv(process.env.PER_MODEL_QUOTA_ENABLED),
  // ---- P8 Observability ----
  prometheusEnabled: (() => {
    const v = process.env.PROMETHEUS_ENABLED;
    if (v === undefined) return true; // enabled by default, no auth
    return parseBoolEnv(v);
  })(),
  // ---- P8 BYOK ----
  byokEnabled: (() => {
    const v = process.env.BYOK_ENABLED;
    if (v === undefined) return true;
    return parseBoolEnv(v);
  })(),
  // ---- P8 Local embedding ----
  localEmbeddingEnabled: parseBoolEnv(process.env.LOCAL_EMBEDDING_ENABLED),
  localEmbeddingModel: (process.env.LOCAL_EMBEDDING_MODEL || "Xenova/bge-small-en-v1.5").trim(),
  // ---- P8 MCP ----
  mcpEnabled: parseBoolEnv(process.env.MCP_ENABLED),
  // ---- P8 Compare ----
  compareMaxConcurrency: (() => {
    const v = parseInt(process.env.COMPARE_MAX_CONCURRENCY || "3", 10);
    return isNaN(v) || v <= 0 ? 3 : Math.min(v, 5);
  })(),
  // ---- P8 Alerts ----
  alertWebhookUrl: (process.env.ALERT_WEBHOOK_URL || "").trim(),
  alertThresholdErrorRate: (() => {
    const v = parseFloat(process.env.ALERT_THRESHOLD_ERROR_RATE || "0.5");
    return isNaN(v) || v < 0 || v > 1 ? 0.5 : v;
  })(),
  providerKeys: {
    // freellms ids use hyphen, config keys use same slug
    "nvidia-nim": parseKeys(process.env.NVIDIA_API_KEYS),
    openrouter: parseKeys(process.env.OPENROUTER_API_KEYS),
    groq: parseKeys(process.env.GROQ_API_KEYS),
    "ollama-cloud": parseKeys(process.env.OLLAMA_CLOUD_API_KEYS),
    "kilo-code": parseKeys(process.env.KILO_CODE_API_KEYS),
    "github-models": parseKeys(process.env.GITHUB_TOKENS),
    cerebras: parseKeys(process.env.CEREBRAS_API_KEYS),
    "ovhcloud-ai-endpoints": parseKeys(process.env.OVHCLOUD_API_KEYS || process.env.OVH_AI_API_KEYS),
    "google-gemini": parseKeys(process.env.GEMINI_API_KEYS),
    "cloudflare-workers-ai": parseKeys(process.env.CLOUDFLARE_API_TOKEN),
    "llm7-io": parseKeys(process.env.LLM7_API_KEYS),
    kiosapi: parseKeys(process.env.KIOS_API_KEYS),
    modelscope: parseKeys(process.env.MODELSCOPE_API_KEYS),
    "chutes-ai": parseKeys(process.env.CHUTES_API_KEYS),
    "z-ai-zhipu-ai": parseKeys(process.env.Z_AI_API_KEYS),
    experientiallabs: parseKeys(process.env.EXPERIENTIAL_API_KEYS || process.env.EXPERIENTIAL_LABS_API_KEYS),
    kiraai: parseKeys(process.env.KIRAAI_API_KEYS || process.env.KIRA_API_KEYS),
    "agnes-ai": parseKeys(process.env.AGNES_API_KEYS),
    "mistral-ai": parseKeys(process.env.MISTRAL_API_KEYS),
    sambanova: parseKeys(process.env.SAMBANOVA_API_KEYS),
    cohere: parseKeys(process.env.COHERE_API_KEYS),
    "grok-xai": parseKeys(process.env.GROK_API_KEYS || process.env.XAI_API_KEYS),
    siliconflow: parseKeys(process.env.SILICONFLOW_API_KEYS),
    "aion-labs": parseKeys(process.env.AION_API_KEYS),
    opencode: parseKeys(process.env.OPENCODE_API_KEYS),
    deepseek: parseKeys(process.env.DEEPSEEK_API_KEYS),
    "alibaba-cloud-model-studio": parseKeys(process.env.ALIBABA_API_KEYS),
    nscale: parseKeys(process.env.NSCALE_API_KEYS),
    nebius: parseKeys(process.env.NEBIUS_API_KEYS),
    "ai21-labs": parseKeys(process.env.AI21_API_KEYS),
    // custom from opencode.json (user)
    orcarouter: parseKeys(process.env.ORCAROUTER_API_KEYS),
    freeai: parseKeys(process.env.FREEAI_API_KEYS),
    cline: parseKeys(process.env.CLINE_API_KEYS),
    "b-ai": parseKeys(process.env.BAI_API_KEYS || process.env.B_AI_API_KEYS),
    tokenharbor: parseKeys(process.env.TOKENHARBOR_API_KEYS || process.env.TOKEN_HARBOR_API_KEYS),
    unorouter: parseKeys(process.env.UNOROUTER_API_KEYS),
    anthropic: parseKeys(process.env.ANTHROPIC_API_KEYS || process.env.CLAUDE_API_KEYS),
    "claude-code": parseKeys(process.env.CLAUDE_CODE_API_KEYS || process.env.ANTHROPIC_API_KEYS || process.env.CLAUDE_API_KEYS),
    codex: parseKeys(process.env.CODEX_API_KEYS || process.env.OPENAI_API_KEYS),
    // legacy / scraped
    together: parseKeys(process.env.TOGETHER_API_KEYS),
    fireworks: parseKeys(process.env.FIREWORKS_API_KEYS),
    novita: parseKeys(process.env.NOVITA_API_KEYS),
    pollinations: parseKeys(process.env.POLLINATIONS_API_KEY),
  } as Record<string, string[]>,
};

export const isPostgres = config.databaseUrl.startsWith("postgres");

// Production hardening warnings (fail-open with warn, not crash, to keep DX).
if (config.nodeEnv === "production") {
  if (config.corsOrigin === "*") {
    console.warn("[config] WARNING: CORS_ORIGIN=* in production — restrict to https://yourdomain.com");
  }
  if (process.env.NODE_TLS_REJECT_UNAUTHORIZED === "0") {
    console.warn("[config] WARNING: NODE_TLS_REJECT_UNAUTHORIZED=0 disables TLS verification — remove in production (use NODE_EXTRA_CA_CERTS)");
  }
  if ((process.env.EXPOSE_BOOTSTRAP ?? "0") !== "0") {
    console.warn("[config] WARNING: EXPOSE_BOOTSTRAP is enabled in production — /api/bootstrap exposes MASTER_KEY. Set EXPOSE_BOOTSTRAP=0");
  }
}
