export const baseUrls: Record<string, string> = {
  "nvidia-nim": "https://integrate.api.nvidia.com/v1",
  nvidia: "https://integrate.api.nvidia.com/v1",
  groq: "https://api.groq.com/openai/v1",
  cerebras: "https://api.cerebras.ai/v1",
  "github-models": "https://models.github.ai/inference",
  "ovhcloud-ai-endpoints": "https://oai.endpoints.kepler.ai.cloud.ovh.net/v1",
  cohere: "https://api.cohere.ai/compatibility/v1",
  "mistral-ai": "https://api.mistral.ai/v1",
  mistral: "https://api.mistral.ai/v1",
  "cloudflare-workers-ai": "https://api.cloudflare.com/client/v4/accounts/{account_id}/ai/v1",
  modelscope: "https://api-inference.modelscope.cn/v1",
  "chutes-ai": "https://api.chutes.ai/v1",
  chutes: "https://llm.chutes.ai/v1",
  sambanova: "https://api.sambanova.ai/v1",
  siliconflow: "https://api.siliconflow.cn/v1",
  "glhf-chat": "https://glhf.chat/api/openai/v1",
  glhf: "https://glhf.chat/api/openai/v1",
  "kilo-code": "https://api.kilo.ai/api/gateway",
  opencode: "https://opencode.ai/zen/v1",
  "llm7-io": "https://api.llm7.io/v1",
  "agnes-ai": "https://apihub.agnes-ai.com/v1",
  "aion-labs": "https://api.aionlabs.ai/v1",
  "z-ai-zhipu-ai": "https://api.z.ai/api/paas/v4",
  experientiallabs: "https://api.experientiallabs.ai/v1",
  experiential: "https://api.experientiallabs.ai/v1",
  "experiential-cloud": "https://api.experientiallabs.ai/v1",
  experiential_cloud: "https://api.experientiallabs.ai/v1",
  kiraai: "https://kiraai.vn/api/v1",
  kira: "https://kiraai.vn/api/v1",
  "b-ai": "https://api.b.ai/v1",
  bai: "https://api.b.ai/v1",
  "chat-b-ai": "https://api.b.ai/v1",
  tokenharbor: "https://tokenharbor.ai/v1",
  "grok-xai": "https://api.x.ai/v1",
  xai: "https://api.x.ai/v1",
  deepseek: "https://api.deepseek.com/v1",
  openrouter: "https://openrouter.ai/api/v1",
  "ollama-cloud": "https://api.ollama.com",
  "alibaba-cloud-model-studio": "https://dashscope.aliyuncs.com/compatible-mode/v1",
  nscale: "https://api.nscale.com/v1",
  nebius: "https://api.studio.nebius.com/v1",
  "ai21-labs": "https://api.ai21.com/studio/v1",
  together: "https://api.together.xyz/v1",
  fireworks: "https://api.fireworks.ai/inference/v1",
  novita: "https://api.novita.ai/v3/openai",
  pollinations: "https://text.pollinations.ai/openai",
  "google-gemini": "https://generativelanguage.googleapis.com/v1beta",
  gemini: "https://generativelanguage.googleapis.com/v1beta",
  orcarouter: "https://api.orcarouter.ai/v1",
  freeai: "https://api.free.ai/v1",
  cline: "https://api.cline.bot/api/v1",
  unorouter: "https://api.unorouter.com/v1",
  anthropic: "https://api.anthropic.com/v1",
  "claude-code": "https://api.anthropic.com/v1",
  codex: "https://api.openai.com/v1",
};

export function getBaseUrl(slug: string): string {
  return baseUrls[slug] || "";
}
